#!/bin/bash

echo ""
echo "🧠 GIT CHEAT SHEET - najčešće komande"
echo "--------------------------------------"
echo ""
echo "1️⃣  Kreiraj novu granu i pređi na nju:"
echo "    git checkout -b naziv-grane"
echo ""
echo "2️⃣  Pogledaj sve grane:"
echo "    git branch"
echo ""
echo "3️⃣  Vrati se na master/main:"
echo "    git checkout master"
echo ""
echo "4️⃣  Spoji granu u master (dok si na masteru):"
echo "    git merge naziv-grane"
echo ""
echo "5️⃣  Obriši lokalnu granu:"
echo "    git branch -d naziv-grane"
echo "    (ili -D ako je ne-merged)"
echo ""
echo "6️⃣  Obriši granu na GitHub-u:"
echo "    git push origin --delete naziv-grane"
echo ""
echo "7️⃣  Gurni lokalnu granu na GitHub:"
echo "    git push --set-upstream origin naziv-grane"
echo ""
echo "8️⃣  Status i šta je promijenjeno:"
echo "    git status"
echo ""
echo "9️⃣  Dodaj sve i komituj:"
echo "    git add ."
echo "    git commit -m \"Opis promjene\""
echo ""
echo "🔟  Gurni promjene na remote (npr. GitHub):"
echo "    git push"
echo ""
echo "🧹 Obriši sve local izmjene i resetuj:"
echo "    git reset --hard"
echo "    git clean -fd"
echo ""

echo "✅ Spremno! Idi peglaj kod kao šef 😎"
